FROM python:3.8
# Set the working directory inside the container
WORKDIR /app/workers
# Copy only the requirements.txt file to the container, to optimize build caching
COPY ./requirements.txt ./requirements.txt
# Install the Python packages listed in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt
